name: mindmap_app
description: Mindmap desktop (diagram + text view) with tags and local JSON save/load.
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  file_selector: ^1.0.3
  path_provider: ^2.1.3
  uuid: ^4.4.0

flutter:
  uses-material-design: true
